name: Linting
on:
  pull_request:

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: File Changes
      id: file_changes
      uses: trilom/file-changes-action@v1.2.3

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        files: '${{ steps.file_changes.outputs.files_modified }}' 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: run linter
      run: python .github/vyos-linter.py '${{ steps.file_changes.outputs.files_modified }}'

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    
